package:
  name: tldr-server
  version: 0.0.0

source:
  path: ..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.6*
    - setuptools
  run:
    - python 3.6*
    - flask
    - invoke
